In [2]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

import numpy as np
spisok = np.arange(10) 
print (spisok)
reversed_spisok = np.flipud(spisok)
print (reversed_spisok)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [5]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

n = int(input ('введи круглое число, которые делится на 10 ='))
a = np.arange(n).reshape(5, 6)
reversed_a = np.flipud(a)
print (reversed_a)


введи круглое число, которые делится на 10 =30
[[24 25 26 27 28 29]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]


array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  0, 17,  0,  0],
       [ 0,  0,  0,  0, 32,  0],
       [ 0,  0,  0,  0,  0, 47],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [2]:
import numpy as np
np.diag(np.arange(1, 50, 15), k=0)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
import numpy as np
n = int(input ('введи круглое число, которые делится на 10 ='))
np.diag(np.arange(n, 0, 5), k=0)

введи круглое число, которые делится на 10 =50


array([], shape=(0, 0), dtype=int32)

In [13]:
#Задание 3
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3


# коэффициенты при переменных в левой части уравнения

a = np.array([[1, 3], [5, 4]])
b = np.array([12, -3])
from numpy import linalg
linalg.solve(a, b)


array([-5.18181818,  5.72727273])

In [14]:
np.allclose( np.dot(a, linalg.solve(a, b)), b ) #проверка решения


True

In [23]:
#Задание 4
#В материалах занятия раздел “Задача 4 домашнего задания”
import numpy as np
import matplotlib.pyplot as plt
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


a1 = np.array([2, 1, 0, 0, 0, 0])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a1, b ):
    """
    Подсчет косинуса угла между векторами a1, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm( a1 )
    bLength = np.linalg.norm( b )
    
    return np.dot( a1, b ) / ( aLength * bLength )
cosine( a1, b )

0.19999999999999996

In [24]:
a2 = np.array([1, 1, 2, 1, 0, 0])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a2, b ):
    """
    Подсчет косинуса угла между векторами a2, b по их координатам
    """ 
    # длины векторов
    aLength = np.linalg.norm( a2)
    bLength = np.linalg.norm( b )
    
    return np.dot( a2, b ) / ( aLength * bLength )
cosine( a2, b )

0.8451542547285165

In [25]:
a3 = np.array([2, 0, 1, 0, 0, 0])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a3, b ):
    """
    Подсчет косинуса угла между векторами a3, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a3)
    bLength = np.linalg.norm( b )
    
    return np.dot( a3, b ) / ( aLength * bLength )
cosine( a3, b )

0.3999999999999999

In [10]:
a4 = np.array([1, 1, 2, 1, 0, 1])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты

def cosine( a4, b ):
    """
    Подсчет косинуса угла между векторами a4, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm( a4 )
    bLength = np.linalg.norm( b )
    
    return np.dot( a4, b ) / ( aLength * bLength )
cosine( a4, b )

0.7905694150420948

In [35]:
a5 = np.array([0, 0, 1, 2, 0, 0])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a5, b ):
    """
    Подсчет косинуса угла между векторами a5, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a5 )
    bLength = np.linalg.norm( b )
    
    return np.dot( a5, b ) / ( aLength * bLength )
cosine( a5, b )

0.3999999999999999

In [28]:
a6 = np.array([0, 0, 0, 0, 0, 5])  
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a6, b ):
    """
    Подсчет косинуса угла между векторами a6, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm( a6 )
    bLength = np.linalg.norm( b )
    
    return np.dot( a6, b ) / ( aLength * bLength )
cosine( a6, b )

0.0

In [34]:
a7 = np.array([1, 0, 0, 0, 0, 0])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a7, b ):
    """
    Подсчет косинуса угла между векторами a7, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a7 )
    bLength = np.linalg.norm( b )
    
    return np.dot( a7, b ) / ( aLength * bLength )
cosine( a7, b )

0.0

In [33]:
a8 = np.array([1, 0, 0, 0, 0, 0])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a8, b ):
    """
    Подсчет косинуса угла между векторами a8, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a8 )
    bLength = np.linalg.norm( b )
    
    return np.dot( a8, b ) / ( aLength * bLength )
cosine( a8, b )

0.0

In [32]:
a9 = np.array([1, 0, 0, 2, 1, 4])
b = np.array([0, 1, 2, 0, 0, 0]) #На сайт заходит очередной посетитель, о покупках которого известно следующие координаты
def cosine( a9, b ):
    """
    Подсчет косинуса угла между векторами a9, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a9 )
    bLength = np.linalg.norm( b )
    
    return np.dot( a9, b ) / ( aLength * bLength )
cosine( a9, b )

0.0

In [ ]:
# Вывод вектор a2 = np.array([1, 1, 2, 1, 0, 0]) с координатами наиболее близок к искомому b = np.array([0, 1, 2, 0, 0, 0]) 